"""Native stateless APIs; original signed model blocks remain in the private wire.

Protocols: platform.claude.com/docs/en/api/messages/create and
ai.google.dev/api/generate-content (checked 2026-09-12). Model limits and
supported thinking options belong to the provider catalog, not this transport.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any
from urllib.parse import quote

from .adapters import JsonAPI, ProviderFailure, encode_state, rate_limit_delay
from .domain import ContextCapacity, encode, identity


def _state(context):
    return {
        k: v
        for k, v in context.items()
        if k not in {"system", "tools", "tool_versions", "provider"}
    }


def _result(observation):
    result = observation["result"]
    if len(encode(result)) > 12000:
        return {
            "observation_ref": observation["_ref"],
            "body_omitted": True,
            "instruction": "Use read_artifact_range",
        }
    return {"observation_ref": observation["_ref"], "result": result}


def _data(raw, provider):
    if raw.get("http_status") != 200:
        raise ProviderFailure(provider, raw.get("http_status", 0))
    if not isinstance(raw.get("data"), dict):
        raise ValueError("invalid native response JSON")
    return raw["data"]


class _Native:
    retry_delay = staticmethod(rate_limit_delay)

    @staticmethod
    def retry_on_resume(raw):
        return raw.get("http_status") in {401, 402, 403} or raw.get("error_kind") in {
            "quota",
            "authentication",
        }

    def __init__(self, api, model, max_tokens, context_tokens, stream, options):
        if stream:
            raise ValueError(
                "native streaming is not implemented; select non-streaming"
            )
        if not isinstance(model, str) or not model.strip():
            raise ValueError("model ID required")
        if (
            type(max_tokens) is not int
            or max_tokens < 1
            or type(context_tokens) is not int
            or context_tokens <= max_tokens
        ):
            raise ValueError("context capacity must exceed positive output allowance")
        self.api, self.model = api, model
        self.max_tokens, self.context_tokens = max_tokens, context_tokens
        self.options = deepcopy(options)
        self.identity = identity(
            self.resource,
            "native-v1",
            api.account,
            model,
            max_tokens,
            context_tokens,
            options,
        )

    def prepare(self, context: dict[str, Any], previous: dict | None) -> dict:
        state = _state(context)
        payload = self._payload(context, state)
        mode, calls = "new", []
        if previous and {
            k: v for k, v in previous["request"].items() if k != self.history_key
        } != {k: v for k, v in payload.items() if k != self.history_key}:
            previous, mode = None, "rebuilt"
        if previous:
            try:
                decoded = self.decode(previous["response"])
            except (ProviderFailure, ValueError, KeyError, TypeError, IndexError):
                decoded = {"complete": False}
            if decoded["complete"]:
                assistant, calls = self._assistant(previous["response"])
                observations = {
                    o["index"]: o for o in previous["observations"] if "index" in o
                }
                if any(i not in observations for i in range(len(calls))):
                    raise ValueError("cannot continue unpaired native tool call")
                old = previous["request"]
                history = deepcopy(old[self.history_key])
                # Public context is regenerated by the Harness. Retain only changed
                # fields and artifacts not already present in this native history.
                prior_state, seen = {}, set()
                for message in history:
                    if message["role"] != "user":
                        continue
                    for value in self._public_values(message):
                        if "observation_ref" in value and "result" in value:
                            seen.add(value["observation_ref"])
                        else:
                            prior_state.update(value)
                            seen.update(
                                i["ref"]
                                for i in value.get("context", [])
                                if "body" in i
                            )
                outputs = [_result(observations[i]) for i in range(len(calls))]
                seen.update(o["observation_ref"] for o in outputs if "result" in o)
                delta = {
                    k: v
                    for k, v in state.items()
                    if k != "context" and prior_state.get(k) != v
                }
                delta["context"] = [
                    i for i in state.get("context", []) if i["ref"] not in seen
                ]
                payload[self.history_key] = [
                    *history,
                    assistant,
                    self._user(delta, calls, outputs),
                ]
                mode = "continued"
        estimated = len(encode(payload).encode("utf-8"))
        if mode == "continued":
            old = previous["request"]
            old_count = self._prompt_tokens(previous["response"])
            if old_count is not None and {
                k: v for k, v in old.items() if k != self.history_key
            } == {k: v for k, v in payload.items() if k != self.history_key}:
                estimated = old_count + len(
                    encode(
                        payload[self.history_key][len(old[self.history_key]) :]
                    ).encode("utf-8")
                )
        if estimated + self.max_tokens > self.context_tokens:
            # Every requested tool has a paired receipt above. A new public-state
            # conversation may now replace the whole exchange; never carry an
            # isolated signature or an unanswered tool call across the rebuild.
            payload = self._payload(context, state)
            estimated = len(encode(payload).encode("utf-8"))
            mode = "rebuilt"
        if estimated + self.max_tokens > self.context_tokens:
            raise ContextCapacity("essential context exceeds provider window")
        return {
            "payload": payload,
            "window_mode": mode,
            "estimated_input_tokens": estimated,
        }

    @staticmethod
    def _parse_text(value):
        import json

        try:
            parsed = json.loads(value)
            return parsed if isinstance(parsed, dict) else {}
        except (ValueError, TypeError):
            return {}


class Anthropic(_Native):
    resource = "anthropic"
    history_key = "messages"

    def __init__(
        self,
        api: JsonAPI,
        model: str,
        *,
        max_tokens: int,
        context_tokens: int,
        thinking: dict | None = None,
        effort: str | None = None,
        stream: bool = False,
    ):
        options = {}
        if thinking is not None:
            if thinking.get("type") not in {"adaptive", "enabled", "disabled"}:
                raise ValueError("invalid Anthropic thinking mode")
            if thinking["type"] == "enabled" and (
                type(thinking.get("budget_tokens")) is not int
                or not 1024 <= thinking["budget_tokens"] < max_tokens
            ):
                raise ValueError(
                    "manual thinking budget must be >=1024 and below output allowance"
                )
            options["thinking"] = thinking
        if effort is not None:
            if effort not in {"low", "medium", "high", "xhigh", "max"}:
                raise ValueError("invalid Anthropic effort")
            options["output_config"] = {"effort": effort}
        super().__init__(api, model, max_tokens, context_tokens, stream, options)

    def _payload(self, context, state):
        return {
            "model": self.model,
            "system": context["system"],
            "messages": [self._user(state, [], [])],
            "tools": [
                {
                    "name": name,
                    "description": spec["description"],
                    "input_schema": spec["parameters"],
                }
                for name, spec in sorted(context["tools"].items())
            ],
            "max_tokens": self.max_tokens,
            **deepcopy(self.options),
        }

    @staticmethod
    def _user(state, calls, outputs):
        blocks = [
            {
                "type": "tool_result",
                "tool_use_id": call["id"],
                "content": encode(result),
                **({"is_error": True} if "error" in result.get("result", {}) else {}),
            }
            for call, result in zip(calls, outputs)
        ]
        return {
            "role": "user",
            "content": [*blocks, {"type": "text", "text": encode_state(state)}],
        }

    def _public_values(self, message):
        return [
            self._parse_text(
                block.get("text") if block["type"] == "text" else block.get("content")
            )
            for block in message["content"]
            if block["type"] in {"text", "tool_result"}
        ]

    def _assistant(self, raw):
        blocks = _data(raw, self.resource)["content"]
        return {"role": "assistant", "content": deepcopy(blocks)}, [
            b for b in blocks if b["type"] == "tool_use"
        ]

    @staticmethod
    def _prompt_tokens(raw):
        usage = raw.get("data", {}).get("usage", {})
        count = usage.get("input_tokens")
        if type(count) is not int or count < 0:
            return None
        return (
            count
            + usage.get("cache_creation_input_tokens", 0)
            + usage.get("cache_read_input_tokens", 0)
        )

    async def complete(self, request):
        return await self.api.post("/messages", request["wire"]["payload"])

    def decode(self, raw):
        data = _data(raw, self.resource)
        blocks = data.get("content")
        if not isinstance(blocks, list):
            raise ValueError("invalid Anthropic content")
        text, calls, ids = [], [], set()
        for block in blocks:
            if not isinstance(block, dict):
                raise ValueError("invalid Anthropic block")
            kind = block.get("type")
            if kind == "text":
                if not isinstance(block.get("text"), str):
                    raise ValueError("invalid Anthropic text")
                text.append(block["text"])
            elif kind == "tool_use":
                name, args, call_id = (
                    block.get("name"),
                    block.get("input"),
                    block.get("id"),
                )
                if (
                    not isinstance(name, str)
                    or not name
                    or not isinstance(args, dict)
                    or not isinstance(call_id, str)
                    or not call_id
                    or call_id in ids
                ):
                    raise ValueError("invalid Anthropic tool call")
                ids.add(call_id)
                calls.append({"name": name, "arguments": args})
            elif kind not in {"thinking", "redacted_thinking"}:
                raise ValueError("unsupported Anthropic content block")
        return {
            "text": "".join(text),
            "calls": calls,
            "complete": data.get("stop_reason") in {"end_turn", "tool_use"},
        }


class Gemini(_Native):
    resource = "gemini"
    history_key = "contents"

    def __init__(
        self,
        api: JsonAPI,
        model: str,
        *,
        max_tokens: int,
        context_tokens: int,
        thinking_level: str | None = None,
        thinking_budget: int | None = None,
        stream: bool = False,
    ):
        if thinking_level is not None and thinking_budget is not None:
            raise ValueError("choose thinking level or budget, not both")
        options = {}
        if thinking_level is not None:
            if thinking_level not in {"minimal", "low", "medium", "high"}:
                raise ValueError("invalid Gemini thinking level")
            options["thinkingConfig"] = {"thinkingLevel": thinking_level}
        if thinking_budget is not None:
            if type(thinking_budget) is not int or thinking_budget < -1:
                raise ValueError("invalid Gemini thinking budget")
            options["thinkingConfig"] = {"thinkingBudget": thinking_budget}
        super().__init__(api, model, max_tokens, context_tokens, stream, options)

    def _payload(self, context, state):
        return {
            "systemInstruction": {"parts": [{"text": context["system"]}]},
            "contents": [self._user(state, [], [])],
            "tools": [
                {
                    "functionDeclarations": [
                        {
                            "name": name,
                            "description": spec["description"],
                            "parametersJsonSchema": spec["parameters"],
                        }
                        for name, spec in sorted(context["tools"].items())
                    ]
                }
            ],
            "generationConfig": {
                "maxOutputTokens": self.max_tokens,
                "candidateCount": 1,
                **deepcopy(self.options),
            },
        }

    @staticmethod
    def _user(state, calls, outputs):
        parts = [
            {
                "functionResponse": {
                    "name": call["name"],
                    "response": result,
                    **({"id": call["id"]} if "id" in call else {}),
                }
            }
            for call, result in zip(calls, outputs)
        ]
        return {"role": "user", "parts": [*parts, {"text": encode_state(state)}]}

    def _public_values(self, message):
        return [
            self._parse_text(part["text"])
            if "text" in part
            else part.get("functionResponse", {}).get("response", {})
            for part in message["parts"]
        ]

    def _assistant(self, raw):
        content = _data(raw, self.resource)["candidates"][0]["content"]
        return deepcopy(content), [
            p["functionCall"] for p in content["parts"] if "functionCall" in p
        ]

    @staticmethod
    def _prompt_tokens(raw):
        count = raw.get("data", {}).get("usageMetadata", {}).get("promptTokenCount")
        return count if type(count) is int and count >= 0 else None

    async def complete(self, request):
        return await self.api.post(
            "/models/" + quote(self.model, safe="") + ":generateContent",
            request["wire"]["payload"],
        )

    def decode(self, raw):
        data = _data(raw, self.resource)
        candidates = data.get("candidates", [])
        if not candidates and data.get("promptFeedback", {}).get("blockReason"):
            return {"text": "", "calls": [], "complete": False}
        if not isinstance(candidates, list) or len(candidates) != 1:
            raise ValueError("expected one Gemini candidate")
        candidate = candidates[0]
        content = candidate.get("content", {"role": "model", "parts": []})
        if content.get("role", "model") != "model" or not isinstance(
            content.get("parts"), list
        ):
            raise ValueError("invalid Gemini content")
        text, calls, ids = [], [], set()
        for part in content["parts"]:
            if not isinstance(part, dict):
                raise ValueError("invalid Gemini part")
            if "functionCall" in part:
                call = part["functionCall"]
                if (
                    not isinstance(call, dict)
                    or not isinstance(call.get("name"), str)
                    or not call["name"]
                    or not isinstance(call.get("args", {}), dict)
                ):
                    raise ValueError("invalid Gemini function call")
                if "id" in call:
                    if (
                        not isinstance(call["id"], str)
                        or not call["id"]
                        or call["id"] in ids
                    ):
                        raise ValueError("invalid Gemini function ID")
                    ids.add(call["id"])
                calls.append({"name": call["name"], "arguments": call.get("args", {})})
            elif "text" in part:
                if not isinstance(part["text"], str):
                    raise ValueError("invalid Gemini text")
                if not part.get("thought"):
                    text.append(part["text"])
            else:
                raise ValueError("unsupported Gemini response part")
        return {
            "text": "".join(text),
            "calls": calls,
            "complete": candidate.get("finishReason") == "STOP",
        }
